nc: 80
scales:
  l: [1.00, 1.00, 1024]

backbone:
  - [-1, 1, Conv, [64, 3, 2]]
  - [-1, 1, Conv, [128, 3, 2]]
  - [-1, 1, RepC3, [128, 0.5]]
  - [-1, 1, Conv, [256, 3, 2]]
  - [-1, 1, RepC3, [256, 0.5]]
  - [-1, 1, Conv, [384, 3, 2]]
  - [-1, 1, RepC3, [384, 1.0]]
  - [-1, 1, Conv, [384, 3, 2]]
  - [-1, 3, RepC3, [384, 1.0]]

head:
  - [-1, 1, Conv, [256, 1, 1, None, 1, 1, False]]
  - [-1, 1, AIFI, [1024, 8]]
  - [-1, 1, RepC3, [256, 0.5]]
  - [[11, 11, 11], 1, RTDETRDecoder, [nc, 256, 300, 4, 8, 3]]

